# Generated by Django 5.2.15 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_withdrawalrequest_payment_wallet_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet_pending_reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
