# Generated by Django 5.2.15 on 2026-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teachersubject_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='booking_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20),
        ),
    ]
