# Generated by Django 5.2.15 on 2026-07-17 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0004_teacherprofile_booking_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='default price'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='subjects.gradelevel', verbose_name='grade level'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='group_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='group capacity'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='lesson_type',
            field=models.CharField(choices=[('one_to_one', 'One-to-one'), ('group', 'Group')], max_length=20, verbose_name='lesson type'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='price_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='maximum price'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='price_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='minimum price'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='subjects.subject', verbose_name='subject'),
        ),
    ]
