# Generated by Django 5.2.15 on 2026-07-05 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0004_teacherprofile_booking_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('one_to_one', 'One-to-one'), ('group', 'Group')], max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('teacher_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('pending_teacher_acceptance', 'Pending teacher acceptance'), ('teacher_rejected', 'Teacher rejected'), ('awaiting_student_payment', 'Awaiting student payment'), ('pending_payment', 'Pending payment'), ('awaiting_receipt_verification', 'Awaiting receipt verification'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled_by_student', 'Cancelled by student'), ('cancelled_by_teacher', 'Cancelled by teacher'), ('rescheduled', 'Rescheduled'), ('no_show_student', 'No-show student'), ('no_show_teacher', 'No-show teacher'), ('disputed', 'Disputed')], default='pending_payment', max_length=40)),
                ('booking_mode', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('meeting_url', models.URLField(blank=True)),
                ('attendance_code', models.CharField(blank=True, max_length=20)),
                ('attendance_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='subjects.gradelevel')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_bookings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='student_bookings', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='subjects.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='teachers.teacherprofile')),
                ('teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='teachers.teachersubject')),
            ],
            options={
                'ordering': ['-scheduled_start'],
                'indexes': [models.Index(fields=['teacher', 'scheduled_start', 'scheduled_end'], name='bookings_bo_teacher_b2622e_idx'), models.Index(fields=['student', 'scheduled_start'], name='bookings_bo_student_70c3d9_idx'), models.Index(fields=['booking_status'], name='bookings_bo_booking_9deb2e_idx')],
            },
        ),
    ]
