# Generated by Django 5.2.15 on 2026-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='wallet_settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
