# Generated by Django 5.2.15 on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_wallet_settled_at'),
        ('teachers', '0004_teacherprofile_booking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_bookings', to='bookings.booking'),
        ),
        migrations.CreateModel(
            name='TeacherBookingViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('cancellation', 'Cancellation'), ('reschedule', 'Reschedule')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_violations', to='bookings.booking')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_violations', to='teachers.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'created_at'], name='bookings_te_teacher_443ad2_idx'), models.Index(fields=['booking', 'violation_type'], name='bookings_te_booking_267a37_idx')],
            },
        ),
    ]
